provide a way to allow Preferences.jl to work on non-package modules
The aim of this PR is to provide a way to use Preferences.jl for modules
that are defined at runtime. It is useful for for debugging or analysis
purposes.

When we want to debug a package code, we may want to run it as top-level
script, e.g. <https://github.com/JuliaLang/PrecompileTools.jl/issues/11>
```julia
julia> using PrecompileTools

julia> PrecompileTools.verbose[] = true

julia> include("src/XXX.jl") # run XXX.jl as a script to see what gets precompiled
ERROR: LoadError: ArgumentError: Module Main.XXX does not correspond to a loaded package!
Stacktrace:
 [1] get_uuid(m::Module)
   @ Preferences ~/.julia/packages/Preferences/VmJXL/src/utils.jl:8
 ...
```

Currently this does not work since `get_uuid(m)` throws when `m` is not
a proper package (in cases like above, `m` is a submodule of `Main`).

With this commit, we can use `Preferences.uuid_cache` to temporarily
make it work:
```julia
julia> using Preferences, Pkg

julia> Preferences.uuid_cache[Main] =
           Pkg.project().dependencies["XXX"]

julia> include("src/XXX.jl")
```

This is also useful for analysis packages like JET.jl, which analyzes
a package by running its code in the `Main` module.